server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test_microservices
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    datasource-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

